### ISSUE TITLE
submit button hidden in search engine selection tab

### ISSUE THREAD

**Issue by Kroissan** [paulgoio/searx#1]
Hi, 
First i need to tell you that i rlly like your searx theme.
I had an issue concerning the bottom bar in the search engine selection tab. Those three button (save, back and default) are hidden behind the page footer.
Using 89.0.4389.114 (Developer Build, ungoogled-chromium)
![image](https://user-images.githubusercontent.com/66138267/129109799-cea090fd-c1c0-43a8-8cc8-df56ba8f7c22.png)

for now im just deleting the footer when i need to click any of these.

**Comment by MrPaulBlack** [comment]
Hi @Kroissan,
Thank you for your bug report. I fixed the issue in fd42156d3699f77e734b7a323336d4ae050754f2; Closing.
